### PR TITLE
Remove decoration and simplify events.

### PR DESCRIPTION
**Pull request by hamidp**
Now, we will fully create the URLs and queue those up instead of event objects. This gets rid of decoration and a few other unused things.

We really need to Dagger the snowman.

### CODE REVIEW

**Comment by dlew** [comment]
Just to make it clear - instead of storing the events themselves, we basically pre-construct the URL and that's what we send later?

**Comment by hamidp** [comment]
@dlew Yep! The deserializer will take old-style events and build the new style EventOperation. Eventually we can remove that functionality as the clients migrate.

**Comment by dlew** [comment]
Why even do the back compat? We've only just recently started snowman. We could just delete the old code.

(Might be more appropriate in a second PR though.)

**Comment by hamidp** [comment]
@dlew It was very simple to keep it. In a releases we can just rename the backing file and drop the support for previously-serialized events.

**Comment by dlew** [comment]
Alright, then :+1:

**Pull request merged**
