### PR TITLE
Add contexts to events.

### PR DESCRIPTION
**Pull request by hamidp**
Events can now specify their own contexts. If there is a context on the event, it will be emitted. Otherwise, the default context is used.

Consumers can modify this behavior through by overriding any of the following Subject methods: contextsForEvent, decorateEvent and createDefaultEventContexts

### CODE REVIEW

**Comment by dlew** [comment]
The code looks fine but I find the term `contexts` to be really confusing. Aren't they more like payloads?

**Comment by hamidp** [comment]
@dlew Kind of: https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#4-custom-contexts

They are contexts that are delivered as an array of payloads.

**Comment by dlew** [comment]
Oh, it's a snowplow term. Weird.

**Comment by hamidp** [comment]
@dlew Can call it custom contexts, it'd be more aligned with the protocol spec.

**Comment by hamidp** [comment]
@dlew renamed.

**Comment by dlew** [comment]
:+1:

**Pull request merged**
